### ISSUE TITLE
Ubuntu-latest (22.04) does not include mongodb anymore

### ISSUE THREAD

**Issue by Alounv** [Maggi64/mongo-clone-action#1]
For information, the action is broken when runned on `ubuntu-latest` because it has moved to `22.04` and does not include mongodb anymore. We should consider adding the mongodb-tools installation in the action. 
https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu

<img width="809" alt="Screenshot 2022-12-05 at 14 40 37" src="https://user-images.githubusercontent.com/34238160/205651270-b778dc32-998c-4a9a-bc4a-c41980782126.png">
2204-Readme.md

**Comment by boly38** [comment]
@Alounv I'm also interested about having mongotool in github action context for boly38/node-mongotools github project
the link you provide result in 404 ?

**Comment by boly38** [comment]
You could add it using this new action : https://github.com/marketplace/actions/action-mongo-tools

**Comment by Alounv** [comment]
@Maggi64 how do you feel about using `action-mongo-tools` inside `mongo-clone-actions` ?

Alternatively, you could just change the description to advise people to use this action before calling `mongo-clone-actions` when being on ubuntu 22.04 and above.

**Comment by Maggi64** [comment]
Just saw this issue and will look into it

**Comment by Alounv** [comment]
Thanks a lot, that's great!
